<?php

function language_labels(string $language): array {
    $all = [
        'English' => [
            'welcome' => 'Welcome to ChatZone',
            'logout' => 'Logout',
            'friends' => 'Friends',
            'add_friend' => 'Add Friend',
            'settings' => 'Settings',
            'save' => 'Save Changes',
            'send' => 'Send',
            'delete_chat' => 'Delete Chat',
            'empty_chat' => 'No messages yet.',
            'message_placeholder' => 'Type a message...',
            'first_name' => 'First Name',
            'last_name' => 'Last Name',
            'email' => 'Email',
            'language' => 'Language',
            'theme' => 'Theme',
            'background' => 'Background',
            'text_color' => 'Text Color',
            'text_background' => 'Text Background',
            'text_size' => 'Text Size',
            'profile_photo' => 'Profile Photo',
            'back_to_chat' => 'Back to Chat',
            'edit_profile' => 'Edit Profile',
            'small' => 'Small',
            'medium' => 'Medium',
            'large' => 'Large',
            'english' => 'English',
            'arabic' => 'Arabic',
            'french' => 'French',
            'profile_updated' => 'Profile updated successfully.',
            'invalid_image' => 'Uploaded file is not a valid image.',
            'image_too_large' => 'Image size must be less than 2MB.',
            'image_types_only' => 'Only jpg, jpeg, png, gif, webp allowed.',
            'upload_failed' => 'Failed to upload image.',
            'db_update_failed' => 'Database update failed.',
        ],

        'Arabic' => [
            'welcome' => 'مرحبًا بك في ChatZone',
            'logout' => 'تسجيل الخروج',
            'friends' => 'الأصدقاء',
            'add_friend' => 'إضافة صديق',
            'settings' => 'الإعدادات',
            'save' => 'حفظ التغييرات',
            'send' => 'إرسال',
            'delete_chat' => 'حذف المحادثة',
            'empty_chat' => 'لا توجد رسائل بعد.',
            'message_placeholder' => 'اكتب رسالة...',
            'first_name' => 'الاسم الأول',
            'last_name' => 'اسم العائلة',
            'email' => 'البريد الإلكتروني',
            'language' => 'اللغة',
            'theme' => 'اللون الرئيسي',
            'background' => 'الخلفية',
            'text_color' => 'لون النص',
            'text_background' => 'خلفية النص',
            'text_size' => 'حجم النص',
            'profile_photo' => 'الصورة الشخصية',
            'back_to_chat' => 'العودة للدردشة',
            'edit_profile' => 'تعديل الملف الشخصي',
            'small' => 'صغير',
            'medium' => 'متوسط',
            'large' => 'كبير',
            'english' => 'الإنجليزية',
            'arabic' => 'العربية',
            'french' => 'الفرنسية',
            'profile_updated' => 'تم تحديث الملف الشخصي بنجاح.',
            'invalid_image' => 'الملف المرفوع ليس صورة صالحة.',
            'image_too_large' => 'حجم الصورة يجب أن يكون أقل من 2MB.',
            'image_types_only' => 'يسمح فقط بـ jpg, jpeg, png, gif, webp.',
            'upload_failed' => 'فشل رفع الصورة.',
            'db_update_failed' => 'فشل تحديث قاعدة البيانات.',
        ],

        'French' => [
            'welcome' => 'Bienvenue sur ChatZone',
            'logout' => 'Se déconnecter',
            'friends' => 'Amis',
            'add_friend' => 'Ajouter un ami',
            'settings' => 'Paramètres',
            'save' => 'Enregistrer les modifications',
            'send' => 'Envoyer',
            'delete_chat' => 'Supprimer la discussion',
            'empty_chat' => 'Aucun message pour le moment.',
            'message_placeholder' => 'Écrivez un message...',
            'first_name' => 'Prénom',
            'last_name' => 'Nom de famille',
            'email' => 'E-mail',
            'language' => 'Langue',
            'theme' => 'Thème',
            'background' => 'Arrière-plan',
            'text_color' => 'Couleur du texte',
            'text_background' => 'Fond du texte',
            'text_size' => 'Taille du texte',
            'profile_photo' => 'Photo de profil',
            'back_to_chat' => 'Retour au chat',
            'edit_profile' => 'Modifier le profil',
            'small' => 'Petit',
            'medium' => 'Moyen',
            'large' => 'Grand',
            'english' => 'Anglais',
            'arabic' => 'Arabe',
            'french' => 'Français',
            'profile_updated' => 'Profil mis à jour avec succès.',
            'invalid_image' => 'Le fichier téléchargé n’est pas une image valide.',
            'image_too_large' => 'La taille de l’image doit être inférieure à 2MB.',
            'image_types_only' => 'Seuls jpg, jpeg, png, gif, webp sont autorisés.',
            'upload_failed' => 'Échec du téléchargement de l’image.',
            'db_update_failed' => 'Échec de la mise à jour de la base de données.',
        ],
    ];

    return $all[$language] ?? $all['English'];
}
